try{
   let a=Number('m')
   
}
catch(error) {
   console.log('Error :',error)
}
finally{
    console.log('Error or success any way i am running  ')
}